[package]
name = "ee_tools_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.30", features = ["derive"] }
bin_converter = { path = "../bin_converter" }
header_syncer = { path = "../header_syncer" }
